version: '3.8'
services:
#  dineflow-app:
#    image: dineflow-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
#    depends_on:
#      - mongodb
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
