version: '3.8'
services:
  dineflow-app:
    image: dineflow-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://dine_flow:dine_flow@web.v9mdl.mongodb.net/
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
